import { useEffect, useState } from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { Tables } from '@/integrations/supabase/types';
import { Loader2, ChevronLeft, ChevronRight, FileDown } from 'lucide-react';
import jsPDF from 'jspdf';

type Trade = Tables<'trades'>;

const RESULT_VALUES = ['Win', 'Loss', 'Breakeven', 'Partial Win - TP1', 'Partial Win - TP2'];
const SESSION_VALUES = ['London', 'New York', 'Asia', 'NY Lunch'];

function parseSetupTag(setupTag: string | null) {
  if (!setupTag) return { result: null, session: null, setup: null };
  const parts = setupTag.split(',').map(s => s.trim()).filter(Boolean);
  let result: string | null = null;
  let session: string | null = null;
  const setup: string[] = [];
  for (const p of parts) {
    if (RESULT_VALUES.includes(p)) result = p;
    else if (SESSION_VALUES.includes(p)) session = p;
    else setup.push(p);
  }
  return { result, session, setup: setup.join(', ') || null };
}

function getTradeSession(trade: Trade): string | null {
  // Prefer dedicated session column, fall back to parsing setup_tag
  if (trade.session) return trade.session;
  return parseSetupTag(trade.setup_tag).session;
}

type Lang = 'ar' | 'fr' | 'en';

function generatePDF(trades: Trade[], lang: Lang) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = 210;
  const margin = 14;
  const colW = (pageW - margin * 2) / 5;
  let y = 18;

  const L = {
    ar: {
      title: 'TradeSmartDz — تقرير الأداء',
      summary: 'ملخص الأداء',
      bySetup: 'الأداء حسب الإعداد',
      bySession: 'الأداء حسب الجلسة',
      topWins: 'أفضل 5 صفقات رابحة',
      topLosses: 'أسوأ 5 صفقات خاسرة',
      totalTrades: 'إجمالي الصفقات',
      winRate: 'نسبة الربح',
      totalPnl: 'إجمالي الربح والخسارة',
      profitFactor: 'معامل الربح',
      maxDrawdown: 'الحد الأقصى للخسارة',
      setup: 'الإعداد', trades: 'الصفقات', wr: 'نسبة الربح', pnl: 'ربح/خسارة',
      symbol: 'الرمز', direction: 'الاتجاه', profit: 'الربح',
      footer: 'تم الإنشاء بواسطة TradeSmartDz — neuroport.xyz',
    },
    fr: {
      title: 'TradeSmartDz — Rapport de performance',
      summary: 'Résumé des performances',
      bySetup: 'Performance par setup',
      bySession: 'Performance par session',
      topWins: 'Top 5 trades gagnants',
      topLosses: 'Top 5 trades perdants',
      totalTrades: 'Total trades',
      winRate: 'Taux de réussite',
      totalPnl: 'PnL total',
      profitFactor: 'Facteur de profit',
      maxDrawdown: 'Drawdown max',
      setup: 'Setup', trades: 'Trades', wr: 'Taux', pnl: 'PnL',
      symbol: 'Symbole', direction: 'Direction', profit: 'Profit',
      footer: 'Généré par TradeSmartDz — neuroport.xyz',
    },
    en: {
      title: 'TradeSmartDz — Performance Report',
      summary: 'Performance Summary',
      bySetup: 'Performance by Setup',
      bySession: 'Performance by Session',
      topWins: 'Top 5 Winning Trades',
      topLosses: 'Top 5 Losing Trades',
      totalTrades: 'Total Trades',
      winRate: 'Win Rate',
      totalPnl: 'Total PnL',
      profitFactor: 'Profit Factor',
      maxDrawdown: 'Max Drawdown',
      setup: 'Setup', trades: 'Trades', wr: 'Win Rate', pnl: 'PnL',
      symbol: 'Symbol', direction: 'Direction', profit: 'Profit',
      footer: 'Generated by TradeSmartDz — neuroport.xyz',
    },
  }[lang];

  const pageH = 297;
  const checkPage = (needed = 10) => {
    if (y + needed > pageH - 16) { doc.addPage(); y = 18; }
  };

  // ---- Header ----
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(L.title, margin, y);
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(new Date().toLocaleDateString(), margin, y);
  doc.setTextColor(0);
  y += 8;

  // ---- Helper: section heading ----
  const sectionHead = (label: string) => {
    checkPage(14);
    doc.setFillColor(30, 30, 50);
    doc.rect(margin, y, pageW - margin * 2, 7, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255);
    doc.text(label, margin + 2, y + 5);
    doc.setTextColor(0);
    y += 10;
  };

  // ---- Helper: simple table ----
  const tableRow = (cells: string[], bold = false, shade = false) => {
    checkPage(8);
    if (shade) { doc.setFillColor(240, 240, 248); doc.rect(margin, y - 1, pageW - margin * 2, 7, 'F'); }
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(9);
    cells.forEach((cell, i) => doc.text(cell, margin + i * colW + 1, y + 4.5, { maxWidth: colW - 2 }));
    doc.setDrawColor(220);
    doc.line(margin, y + 6, pageW - margin, y + 6);
    y += 7;
  };

  // ---- Section 1: Summary ----
  const closedTrades = trades.filter(tr => tr.profit !== null);
  const wins = closedTrades.filter(tr => (tr.profit ?? 0) > 0);
  const losses = closedTrades.filter(tr => (tr.profit ?? 0) < 0);
  const totalPnl = closedTrades.reduce((s, tr) => s + (tr.profit ?? 0), 0);
  const winRate = closedTrades.length ? (wins.length / closedTrades.length * 100).toFixed(1) : '0';
  const grossProfit = wins.reduce((s, tr) => s + (tr.profit ?? 0), 0);
  const grossLoss = Math.abs(losses.reduce((s, tr) => s + (tr.profit ?? 0), 0));
  const profitFactor = grossLoss > 0 ? (grossProfit / grossLoss).toFixed(2) : '∞';
  let peak = 0, maxDD = 0, running = 0;
  for (const tr of closedTrades) {
    running += tr.profit ?? 0;
    if (running > peak) peak = running;
    const dd = peak > 0 ? (peak - running) / peak * 100 : 0;
    if (dd > maxDD) maxDD = dd;
  }

  sectionHead(L.summary);
  const summaryRows = [
    [L.totalTrades, String(closedTrades.length)],
    [L.winRate, `${winRate}%`],
    [L.totalPnl, `$${totalPnl.toFixed(2)}`],
    [L.profitFactor, profitFactor],
    [L.maxDrawdown, `${maxDD.toFixed(1)}%`],
  ];
  summaryRows.forEach((row, i) => {
    checkPage(8);
    if (i % 2 === 0) { doc.setFillColor(248, 248, 255); doc.rect(margin, y - 1, pageW - margin * 2, 7, 'F'); }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(row[0], margin + 2, y + 4.5);
    doc.setFont('helvetica', 'bold');
    doc.text(row[1], margin + colW * 2, y + 4.5);
    doc.setDrawColor(220);
    doc.line(margin, y + 6, pageW - margin, y + 6);
    y += 7;
  });
  y += 4;

  // ---- Section 2: By Setup ----
  const setupGroups: Record<string, Trade[]> = {};
  for (const tr of trades) {
    const parts = (tr.setup_tag ?? '').split(',').map(s => s.trim()).filter(Boolean);
    const RESULT_V = ['Win', 'Loss', 'Breakeven', 'Partial Win - TP1', 'Partial Win - TP2'];
    const SESSION_V = ['London', 'New York', 'Asia', 'NY Lunch'];
    const setup = parts.filter(p => !RESULT_V.includes(p) && !SESSION_V.includes(p)).join(', ') || 'Other';
    if (!setupGroups[setup]) setupGroups[setup] = [];
    setupGroups[setup].push(tr);
  }
  const setupData = Object.entries(setupGroups).map(([name, ts]) => {
    const w = ts.filter(tr => (tr.profit ?? 0) > 0).length;
    return { name, count: ts.length, wr: `${Math.round(w / ts.length * 100)}%`, pnl: `$${ts.reduce((s, tr) => s + (tr.profit ?? 0), 0).toFixed(2)}` };
  });

  sectionHead(L.bySetup);
  tableRow([L.setup, L.trades, L.wr, L.pnl], true);
  setupData.forEach((row, i) => tableRow([row.name, String(row.count), row.wr, row.pnl], false, i % 2 === 0));
  y += 4;

  // ---- Section 3: By Session ----
  const sessions = ['London', 'New York', 'Asia', 'NY Lunch'];
  const sessionData = sessions.map(ses => {
    const ts = trades.filter(tr => (tr.session ?? parseSetupTag(tr.setup_tag).session) === ses);
    if (!ts.length) return null;
    const w = ts.filter(tr => (tr.profit ?? 0) > 0).length;
    return { name: ses, count: ts.length, wr: `${Math.round(w / ts.length * 100)}%`, pnl: `$${ts.reduce((s, tr) => s + (tr.profit ?? 0), 0).toFixed(2)}` };
  }).filter(Boolean) as { name: string; count: number; wr: string; pnl: string }[];

  sectionHead(L.bySession);
  tableRow([L.setup, L.trades, L.wr, L.pnl], true);
  sessionData.forEach((row, i) => tableRow([row.name, String(row.count), row.wr, row.pnl], false, i % 2 === 0));
  y += 4;

  // ---- Section 4: Top 5 wins / Top 5 losses ----
  const sorted = [...closedTrades].sort((a, b) => (b.profit ?? 0) - (a.profit ?? 0));
  const top5wins = sorted.slice(0, 5);
  const top5losses = sorted.slice(-5).reverse();

  const tradeTable = (label: string, rows: Trade[]) => {
    sectionHead(label);
    tableRow([L.symbol, L.direction, L.profit, 'Date'], true);
    rows.forEach((tr, i) => tableRow([
      tr.symbol,
      tr.direction,
      `$${(tr.profit ?? 0).toFixed(2)}`,
      tr.close_time ? new Date(tr.close_time).toLocaleDateString() : '—',
    ], false, i % 2 === 0));
    y += 4;
  };

  tradeTable(L.topWins, top5wins);
  tradeTable(L.topLosses, top5losses);

  // ---- Footer ----
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(L.footer, margin, pageH - 6);
    doc.text(`${p} / ${totalPages}`, pageW - margin, pageH - 6, { align: 'right' });
  }

  const date = new Date().toISOString().slice(0, 10);
  doc.save(`tradesmartdz-report-${date}.pdf`);
}

const AnalyticsPage = () => {
  const { t, language } = useLanguage();
  const lang = language as Lang;
  const { user } = useAuth();
  const [trades, setTrades] = useState<Trade[]>([]);
  const [loading, setLoading] = useState(true);
  const [timeRange, setTimeRange] = useState('allTime');
  const [calendarMonth, setCalendarMonth] = useState(() => {
    const now = new Date();
    return { year: now.getFullYear(), month: now.getMonth() };
  });
  const [selectedDay, setSelectedDay] = useState<number | null>(null);

  useEffect(() => {
    if (!user) return;
    const fetchTrades = async () => {
      setLoading(true);
      const { data } = await supabase
        .from('trades')
        .select('*')
        .eq('user_id', user.id)
        .order('close_time', { ascending: true });
      setTrades(data ?? []);
      setLoading(false);
    };
    fetchTrades();
  }, [user]);

  const ranges = [
    { key: 'thisWeek', label: t('thisWeek') },
    { key: 'thisMonth', label: t('thisMonth') },
    { key: 'last3Months', label: t('last3Months') },
    { key: 'allTime', label: t('allTime') },
  ];

  const filteredTrades = trades.filter(tr => {
    if (!tr.close_time || timeRange === 'allTime') return true;
    const now = new Date();
    const d = new Date(tr.close_time);
    if (timeRange === 'thisWeek') {
      const start = new Date(now);
      start.setDate(now.getDate() - now.getDay());
      start.setHours(0, 0, 0, 0);
      return d >= start;
    }
    if (timeRange === 'thisMonth') {
      return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
    }
    if (timeRange === 'last3Months') {
      const start = new Date(now);
      start.setMonth(now.getMonth() - 3);
      return d >= start;
    }
    return true;
  });

  // By Setup — group by setup portion of setup_tag
  const setupGroups: Record<string, Trade[]> = {};
  for (const tr of filteredTrades) {
    const { setup } = parseSetupTag(tr.setup_tag);
    const key = setup || 'Other';
    if (!setupGroups[key]) setupGroups[key] = [];
    setupGroups[key].push(tr);
  }
  const bySetup = Object.entries(setupGroups).map(([name, ts]) => {
    const wins = ts.filter(tr => (tr.profit ?? 0) > 0).length;
    return {
      name: name.length > 18 ? name.slice(0, 18) + '…' : name,
      pnl: +ts.reduce((s, tr) => s + (tr.profit ?? 0), 0).toFixed(2),
      winRate: ts.length ? Math.round((wins / ts.length) * 100) : 0,
      count: ts.length,
    };
  }).sort((a, b) => Math.abs(b.pnl) - Math.abs(a.pnl));

  // By Symbol
  const symbolGroups: Record<string, Trade[]> = {};
  for (const tr of filteredTrades) {
    if (!symbolGroups[tr.symbol]) symbolGroups[tr.symbol] = [];
    symbolGroups[tr.symbol].push(tr);
  }
  const bySymbol = Object.entries(symbolGroups).map(([sym, ts]) => ({
    name: sym,
    pnl: +ts.reduce((s, tr) => s + (tr.profit ?? 0), 0).toFixed(2),
    count: ts.length,
  })).sort((a, b) => Math.abs(b.pnl) - Math.abs(a.pnl));

  // By Session — use dedicated session column with fallback to parsed setup_tag
  const sessions = ['London', 'New York', 'Asia', 'NY Lunch'];
  const bySession = sessions.map(ses => {
    const ts = filteredTrades.filter(tr => getTradeSession(tr) === ses);
    const wins = ts.filter(tr => (tr.profit ?? 0) > 0).length;
    return {
      name: ses === 'New York' ? 'NY' : ses,
      pnl: +ts.reduce((s, tr) => s + (tr.profit ?? 0), 0).toFixed(2),
      winRate: ts.length ? Math.round((wins / ts.length) * 100) : 0,
      count: ts.length,
    };
  }).filter(s => s.count > 0);

  // By Day of week
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const byDay = days.map((day, i) => {
    const ts = filteredTrades.filter(tr => tr.close_time && new Date(tr.close_time).getDay() === (i + 1) % 7);
    return { name: day, pnl: +ts.reduce((s, tr) => s + (tr.profit ?? 0), 0).toFixed(2) };
  });

  // Calendar for calendarMonth
  const { year, month } = calendarMonth;
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const firstDayOfWeek = new Date(year, month, 1).getDay(); // 0=Sun

  // Build calendar grid with leading empty cells (Mon-first: shift Sun to end)
  const leadingBlanks = (firstDayOfWeek === 0 ? 6 : firstDayOfWeek - 1);

  const calendarData = Array.from({ length: daysInMonth }, (_, i) => {
    const day = i + 1;
    const dayTrades = filteredTrades.filter(tr => {
      if (!tr.close_time) return false;
      const d = new Date(tr.close_time);
      return d.getFullYear() === year && d.getMonth() === month && d.getDate() === day;
    });
    const pnl = dayTrades.reduce((s, tr) => s + (tr.profit ?? 0), 0);
    const wins = dayTrades.filter(tr => (tr.profit ?? 0) > 0).length;
    return { day, pnl, count: dayTrades.length, wins };
  });

  const selectedDayData = selectedDay !== null ? calendarData[selectedDay - 1] : null;

  const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];

  const prevMonth = () => {
    setCalendarMonth(({ year, month }) => month === 0
      ? { year: year - 1, month: 11 }
      : { year, month: month - 1 });
    setSelectedDay(null);
  };

  const nextMonth = () => {
    setCalendarMonth(({ year, month }) => month === 11
      ? { year: year + 1, month: 0 }
      : { year, month: month + 1 });
    setSelectedDay(null);
  };

  const renderBarChart = (data: { name: string; pnl: number }[], title: string) => (
    <Card className="border-border bg-card">
      <CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader>
      <CardContent>
        {data.length === 0 ? (
          <div className="flex h-[250px] items-center justify-center">
            <p className="text-sm text-muted-foreground">No data yet.</p>
          </div>
        ) : (
          <ResponsiveContainer width="100%" height={250}>
            <BarChart data={data} layout="vertical" margin={{ left: 8, right: 16 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(225, 15%, 20%)" horizontal={false} />
              <XAxis type="number" stroke="hsl(220, 10%, 55%)" fontSize={11} />
              <YAxis dataKey="name" type="category" stroke="hsl(220, 10%, 55%)" fontSize={11} width={90} />
              <Tooltip
                contentStyle={{ backgroundColor: 'hsl(225, 18%, 12%)', border: '1px solid hsl(225, 15%, 20%)', borderRadius: '8px', color: 'hsl(220, 10%, 90%)' }}
                formatter={(val: number) => [`$${val.toFixed(2)}`, 'P&L']}
              />
              <Bar dataKey="pnl" radius={[0, 4, 4, 0]}>
                {data.map((entry, i) => (
                  <Cell key={i} fill={entry.pnl >= 0 ? 'hsl(142, 71%, 45%)' : 'hsl(0, 84%, 60%)'} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        )}
      </CardContent>
    </Card>
  );

  const renderDayChart = (data: { name: string; pnl: number }[], title: string) => (
    <Card className="border-border bg-card">
      <CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader>
      <CardContent>
        {data.every(d => d.pnl === 0) ? (
          <div className="flex h-[250px] items-center justify-center">
            <p className="text-sm text-muted-foreground">No data yet.</p>
          </div>
        ) : (
          <ResponsiveContainer width="100%" height={250}>
            <BarChart data={data}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(225, 15%, 20%)" />
              <XAxis dataKey="name" stroke="hsl(220, 10%, 55%)" fontSize={11} />
              <YAxis stroke="hsl(220, 10%, 55%)" fontSize={11} />
              <Tooltip contentStyle={{ backgroundColor: 'hsl(225, 18%, 12%)', border: '1px solid hsl(225, 15%, 20%)', borderRadius: '8px', color: 'hsl(220, 10%, 90%)' }} formatter={(val: number) => [`$${val.toFixed(2)}`, 'P&L']} />
              <Bar dataKey="pnl" radius={[4, 4, 0, 0]}>
                {data.map((entry, i) => (
                  <Cell key={i} fill={entry.pnl >= 0 ? 'hsl(142, 71%, 45%)' : 'hsl(0, 84%, 60%)'} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        )}
      </CardContent>
    </Card>
  );

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <h1 className="text-2xl font-bold text-foreground">{t('analytics')}</h1>
        <div className="flex flex-wrap gap-2">
          {ranges.map(r => (
            <Button key={r.key} variant={timeRange === r.key ? 'default' : 'outline'} size="sm"
              className={timeRange === r.key ? 'gradient-primary text-primary-foreground' : ''}
              onClick={() => setTimeRange(r.key)}>
              {r.label}
            </Button>
          ))}
          <Button variant="outline" size="sm" onClick={() => generatePDF(filteredTrades, lang)} className="gap-1.5">
            <FileDown className="h-4 w-4" />
            {lang === 'ar' ? 'تحميل التقرير' : lang === 'fr' ? 'Télécharger le rapport' : 'Download Report'}
          </Button>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {renderBarChart(bySetup, t('bySetup'))}
        {renderBarChart(bySymbol, t('bySymbol'))}
        {renderBarChart(bySession, t('bySession'))}
        {renderDayChart(byDay, t('byDay'))}
      </div>

      {/* Monthly Calendar */}
      <Card className="border-border bg-card">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg">{t('monthlyCalendar')}</CardTitle>
            <div className="flex items-center gap-2">
              <button onClick={prevMonth} className="flex h-7 w-7 items-center justify-center rounded hover:bg-secondary">
                <ChevronLeft className="h-4 w-4" />
              </button>
              <span className="min-w-[130px] text-center text-sm font-medium">
                {monthNames[month]} {year}
              </span>
              <button onClick={nextMonth} className="flex h-7 w-7 items-center justify-center rounded hover:bg-secondary">
                <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {/* Day-of-week headers (Mon–Sun) */}
          <div className="mb-2 grid grid-cols-7 gap-1 text-center text-xs text-muted-foreground">
            {['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(d => (
              <div key={d} className="py-1 font-medium">{d}</div>
            ))}
          </div>
          <div className="grid grid-cols-7 gap-1">
            {/* Leading blanks */}
            {Array.from({ length: leadingBlanks }).map((_, i) => (
              <div key={`blank-${i}`} />
            ))}
            {calendarData.map(({ day, pnl, count }) => {
              const isSelected = selectedDay === day;
              let cellClass = 'bg-secondary text-muted-foreground';
              if (count > 0) {
                if (pnl > 0) cellClass = 'bg-profit/20 text-profit hover:bg-profit/30';
                else if (pnl < 0) cellClass = 'bg-loss/20 text-loss hover:bg-loss/30';
                else cellClass = 'bg-yellow-500/20 text-yellow-400 hover:bg-yellow-500/30';
              }
              return (
                <button
                  key={day}
                  type="button"
                  onClick={() => setSelectedDay(selectedDay === day ? null : day)}
                  className={`flex h-10 flex-col items-center justify-center rounded-md text-xs font-medium transition-colors ${cellClass} ${isSelected ? 'ring-2 ring-primary ring-offset-1 ring-offset-card' : ''}`}
                >
                  <span>{day}</span>
                  {count > 0 && <span className="text-[9px] opacity-70">{count}t</span>}
                </button>
              );
            })}
          </div>

          {/* Day detail popover */}
          {selectedDay !== null && selectedDayData && selectedDayData.count > 0 && (
            <div className="mt-4 rounded-lg border border-border bg-secondary/60 p-4">
              <p className="mb-2 text-sm font-semibold">
                {monthNames[month]} {selectedDay}, {year}
              </p>
              <div className="flex gap-6 text-sm">
                <div>
                  <p className="text-muted-foreground">Trades</p>
                  <p className="font-bold">{selectedDayData.count}</p>
                </div>
                <div>
                  <p className="text-muted-foreground">P&L</p>
                  <p className={`font-bold ${selectedDayData.pnl >= 0 ? 'text-profit' : 'text-loss'}`}>
                    {selectedDayData.pnl >= 0 ? '+' : ''}${selectedDayData.pnl.toFixed(2)}
                  </p>
                </div>
                <div>
                  <p className="text-muted-foreground">Win Rate</p>
                  <p className="font-bold">
                    {selectedDayData.count > 0 ? Math.round((selectedDayData.wins / selectedDayData.count) * 100) : 0}%
                  </p>
                </div>
              </div>
            </div>
          )}
          {selectedDay !== null && selectedDayData && selectedDayData.count === 0 && (
            <div className="mt-4 rounded-lg border border-border bg-secondary/60 p-4">
              <p className="text-sm text-muted-foreground">No trades on {monthNames[month]} {selectedDay}.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default AnalyticsPage;
